# Generated by Django 3.0.8 on 2020-08-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
